CC = gcc
CFLAGS = -Wall -Wextra -std=c99
EXEC = tekien
SRC = main.c admin.c etudiant.c
OBJ = $(SRC:.c=.o)

all: $(EXEC)

$(EXEC): $(OBJ)
->$(CC) -o $@ $^

%.o: %.c
->$(CC) $(CFLAGS) -c $<

clean:
->rm -rf *.o

mrproper: clean
->rm -rf $(EXEC)
